tinkerkit:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers and set up PID
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_joint
    pid: {p: 700, i: 50, d: 70}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 700, i: 50, d: 70}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 1700, i: 50, d: 100}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_joint
    pid: {p: 2000, i: 100, d: 150}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: hand_joint
    pid: {p: 2000, i: 100, d: 100}

  gripper_right_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_gripper_joint
    pid: {p: 2500, i: 10, d: 10}

  gripper_left_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_gripper_joint
    pid: {p: 2500, i: 10, d: 10}
